### PR TITLE
Fix #40 async task connection reset after 15 minutes & fix travis

### LINKED ISSUE #40: async task connection reset after 15 minutes
Hi,

I am syncing data from Active Directory and it's working fine in sync
mode but when running in async mode I see the following error in the
log and the data is no longer being synced.

Feb 13 14:18:46 ip-10-0-135-60 sync[12163]: Feb 13 14:18:46 - DEBUG -
Asynchronous synchronize SyncUserTask
Feb 13 14:33:55 ip-10-0-135-60 sync[12163]: Feb 13 14:33:55 - WARN  -
Connection reset by peer
```
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_151]
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_151]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_151]
at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_151]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_151]
at org.apache.mina.transport.socket.nio.NioProcessor.read(NioProcessor.java:273) ~[mina-core-2.0.7.jar:na]
at org.apache.mina.transport.socket.nio.NioProcessor.read(NioProcessor.java:44) ~[mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:690) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124) [mina-core-2.0.7.jar:na]
at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [mina-core-2.0.7.jar:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```
Is the 15 minutes timeout can be configured on the LSC or AD side?
Is there some way to establish the connection again without restarting LSC?

Another thing that I've noticed is that once this exception happens
and I change something in the AD,I get this error:
```
ERROR - LDAP error while reading entry CN=Test User,OU=Users,OU=ad-testing,DC=ad-testing,DC=test,DC=io (org.apache.directory.ldap.client.api.exception.InvalidConnectionException: Cannot connect on the server, the connection is invalid)
DEBUG - org.apache.directory.ldap.client.api.exception.InvalidConnectionException: Cannot connect on the server, the connection is invalid
org.apache.directory.ldap.client.api.exception.InvalidConnectionException: Cannot connect on the server, the connection is invalid
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.checkSession(LdapNetworkConnection.java:271) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.searchAsync(LdapNetworkConnection.java:1667) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.search(LdapNetworkConnection.java:1710) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.search(LdapNetworkConnection.java:1603) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.search(LdapNetworkConnection.java:1613) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.lsc.service.SyncReplSourceService.getBean(SyncReplSourceService.java:250) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:689) [lsc-core-2.1.4.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```

### PR DESCRIPTION
**Pull request by soisik**
This fix re-connect to LDAP during async tasks if connection has timed out.

Currently, task connection is kept forever while running async check, potentially leading to lost connection errors after some times as it is only used when changes are detected :
* Lost connection error :
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_151]
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_151]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_151]
at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_151]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_151]
at org.apache.mina.transport.socket.nio.NioProcessor.read(NioProcessor.java:273) ~[mina-core-2.0.7.jar:na]
at org.apache.mina.transport.socket.nio.NioProcessor.read(NioProcessor.java:44) ~[mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:690) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [mina-core-2.0.7.jar:na]
at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124) [mina-core-2.0.7.jar:na]
at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [mina-core-2.0.7.jar:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

* Following later by async task failure when data that need to be sync is pulled :
ERROR - LDAP error while reading entry CN=Test User,OU=Users,OU=ad-testing,DC=ad-testing,DC=test,DC=io (org.apache.directory.ldap.client.api.exception.InvalidConnectionException: Cannot connect on the server, the connection is invalid)
DEBUG - org.apache.directory.ldap.client.api.exception.InvalidConnectionException: Cannot connect on the server, the connection is invalid
org.apache.directory.ldap.client.api.exception.InvalidConnectionException: Cannot connect on the server, the connection is invalid
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.checkSession(LdapNetworkConnection.java:271) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.searchAsync(LdapNetworkConnection.java:1667) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.search(LdapNetworkConnection.java:1710) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.search(LdapNetworkConnection.java:1603) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.apache.directory.ldap.client.api.LdapNetworkConnection.search(LdapNetworkConnection.java:1613) ~[api-all-1.0.0-M22.jar:1.0.0-M22]
        at org.lsc.service.SyncReplSourceService.getBean(SyncReplSourceService.java:250) ~[lsc-core-2.1.4.jar:na]
        at org.lsc.SynchronizeTask.run(AbstractSynchronize.java:689) [lsc-core-2.1.4.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

Fix detail : After changes are detected, and before changed entry is synchronized, connection.isConnected() is called; It returns the same result as the checkSession() method that throws the connection error (cf https://github.com/apache/directory-ldap-api/blob/2033a9dd83d89774744cc390ff1e5cf608a3d6dd/ldap/client/api/src/main/java/org/apache/directory/ldap/client/api/LdapNetworkConnection.java#L262). If connection.isConnected() returns false, the connection is re-established.

Side remarks : LSC periodically checks for changes to apply (using syncrepl protocol) and seems to be reusing the same connection every time. But that connection doesn't times out since it is called every few seconds (see SyncReplSourceService.getNextId()), while the task connection is only used when an actual change is detected, which can lead to connection timing out.

### CODE REVIEW

File: src/main/java/org/lsc/service/SyncReplSourceService.java [hunk 1]
```diff
@@ -244,7 +247,10 @@ public IBean getBean(final String id, final LscDatasets pivotAttrs, boolean from
             // When launching getBean in clean phase, the search base should be the Base DN, not the entry ID
             String searchBaseDn = (fromSameService ? id : baseDn);
             SearchScope searchScope = (fromSameService ? SearchScope.OBJECT : SearchScope.SUBTREE);
-			if(getAttrs() != null) {
+			if (!connection.isConnected()) {
+				connection = getConnection(ldapConn);
+			}
```
Comment (rouazana) [inline src/main/java/org/lsc/service/SyncReplSourceService.java]: indentation issue?

Comment (soisik) [reply src/main/java/org/lsc/service/SyncReplSourceService.java]: Not that I can see in Github or my IDE. There is a lot of code in LSC indented with spaces instead of tabs, it could lead to format hazard in github diffs. I use tabs only.

**Comment by soisik** [comment]
Hi Raphael, 
I did not change the handling of syncrepl connection that check for updates (it's not that connection that is faulty in the original issue ; it worked well and triggered changes as expected, since it is kept alive as it calls the server every X seconds. What I have changed is the handling of the connection that gets the data when a change is detected (a basic LDAP connection), which is completely distinct from the connexion used by syncrepl. This basic LDAP connection is kept forever and if not used (which will happen if no changes are triggered), it could be lost.
See : 
AsynchronousRunner.run() (embeded in AbstractSynchronize)
SyncReplSourceService.nextId() => use it own connection for searchAsync 
SyncReplSourceService.getBean() => reuse the same connection everytime there's a change, using basic LDAP search

Let me know if I misunderstood the way the code is written.

I'm planning on settings up an environments soon to test syncrepl as there is another issue open, I can test that fix to see if it does not create new issues and does fix the issue #40.

File: src/main/java/org/lsc/service/SyncReplSourceService.java (hunk 1 above)
Comment (rouazana) [reply src/main/java/org/lsc/service/SyncReplSourceService.java]: in github, the (if (!connection...) starts at the same level than the old (if(getAttrs()...).
The new if(getAttrs...) (see below) is not at the same level of indentation. The new level seems better, as it is aligned with SearchScope searchscope...

Comment (rouazana) [reply src/main/java/org/lsc/service/SyncReplSourceService.java]: see this view for example: https://github.com/lsc-project/lsc/pull/42/files

Comment (soisik) [reply src/main/java/org/lsc/service/SyncReplSourceService.java]: I fixed the whole class indentation (replace all dots indents by tabs), https://github.com/lsc-project/lsc/blob/7c062813a40f485c3e92de8e79a81f748af0c15b/src/main/java/org/lsc/service/SyncReplSourceService.java
